// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddGameBook struct {
	GameID     string `json:"game_id"`
	BookNumber string `json:"book_number"`
	ShipmentID string `json:"shipment_id"`
}

type GameBook struct {
	GameID      string `json:"game_id"`
	BookNumber  string `json:"book_number"`
	ShipmentID  string `json:"shipment_id"`
	SignOutDate string `json:"sign_out_date"`
}

type GameType struct {
	GameID      string `json:"game_id"`
	TicketValue string `json:"ticket_value"`
	TicketName  string `json:"ticket_name"`
	BookValue   string `json:"book_value"`
	CurrentGame bool   `json:"current_game"`
}

type NewShipment struct {
	ShipmentID   string `json:"shipment_id"`
	DateReceived string `json:"date_received"`
}

type RemoveGameType struct {
	GameID string `json:"game_id"`
}

type Shipment struct {
	ShipmentID   string `json:"shipment_id"`
	DateReceived string `json:"date_received"`
}

type SignOutGameBook struct {
	GameID      string `json:"game_id"`
	BookNumber  string `json:"book_number"`
	SignOutDate string `json:"sign_out_date"`
}

type UpdateGameType struct {
	GameID      string `json:"game_id"`
	TicketValue string `json:"ticket_value"`
	TicketName  string `json:"ticket_name"`
	BookValue   string `json:"book_value"`
	CurrentGame bool   `json:"current_game"`
}
